<?php
$z[0]=Array("global","\n					if(@me%3=='0')\n					{\n						@me ='<li class=\"right\">';\n					}\n					else\n					{\n						@me ='<li>';\n					}\n					",0,175);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",216,231);
$z[2]=Array("litpic","",243,258);
$z[3]=Array("arcurl","",319,334);
$z[4]=Array("title","",336,350);
$z[5]=Array("price","",413,427);
$z[6]=Array("arcurl","",483,498);

?>