<?php
$z[0]=Array("global","\n					if(@me%3=='0')\n					{\n						@me = '<li>';\n					}\n					else\n					{\n						@me = '<li class=\"right\">';\n					}\n					",0,177);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",218,233);
$z[2]=Array("litpic","",245,260);
$z[3]=Array("arcurl","",321,336);
$z[4]=Array("title","",338,352);
$z[5]=Array("price","",415,429);
$z[6]=Array("arcurl","",485,500);

?>