<?php
$z[0]=Array("global","",105,137);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("arclist","\r\n				linkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\r\n				picarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n				textarr[[field:global.autoindex/]] = \"[field:title function='html2text(@me)'/]\";\r\n				",784,1047);
$z[1][4]['row']="4";
$z[1][4]['typeid']="28";
$z[2]=Array("global","",1683,1715);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2050,2082);
$z[3][4]['name']="cfg_templets_skin";

?>