<?php
$z[0]=Array("global","",319,345);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",396,426);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",463,490);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",525,557);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",583,620);
$z[4][4]['filename']="header.htm";
$z[5]=Array("channel","\n					<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\n					",708,829);
$z[5][4]['typeid']="2";
$z[5][4]['type']="son";
$z[6]=Array("arclist","\n					[field:global name='autoindex' runphp='yes']\n					if(@me%3=='0')\n					{\n						@me = '<li class=\"right\">';\n					}\n					else\n					{\n						@me = '<li>';\n					}\n					[/field:global]\n						<p class=\"p_img\">\n							<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" alt=\"\" /></a>\n						</p>\n						<p class=\"p_title\"><a href=\"[field:arcurl/]\">[field:title/]</a></p>\n						<p class=\"p_price\">\n						产品价格：<em>￥[field:price/]</em>\n						</p>\n						<p class=\"p_buy\">\n						<a href=\"[field:arcurl/]\">\n							在线订购\n						</a>\n						</p>\n					</li>\n					",1003,1651);
$z[6][4]['typeid']="2";
$z[6][4]['row']="6";
$z[6][4]['addfields']="price";
$z[6][4]['channelid']="17";
$z[7]=Array("include","",1683,1719);
$z[7][4]['filename']="right.htm";
$z[8]=Array("include","",1720,1763);
$z[8][4]['filename']="footer_index.htm";

?>